### PR TITLE
Typo fix

### PR DESCRIPTION
**Pull request by qrilka**

### CODE REVIEW

**Comment by Skarlett** [comment]
good catch

**Comment by tnballo** [comment]
Good catch indeed, thank you!

Per [this part of `CONTRIBUTING.md`](https://github.com/tnballo/high-assurance-rust/blob/main/CONTRIBUTING.md#adding-yourself-to-the-community-contributors-list), would you like to add your GitHub username/URL to the Community Contributors list before I merge your PR?

It's like the public repo contributors list, but visible to readers of the website.

**Comment by qrilka** [comment]
Sure

**Comment by qrilka** [comment]
And done

**Comment by tnballo** [comment]
Sweet, thanks!

**Pull request merged**
