### PR TITLE
typo

### PR DESCRIPTION
**Pull request by tshepang**

### CODE REVIEW

**Comment by tnballo** [comment]
Good catch, thank you!

Per [this part of `CONTRIBUTING.md`](https://github.com/tnballo/high-assurance-rust/blob/main/CONTRIBUTING.md#adding-yourself-to-the-community-contributors-list), would you like to add your GitHub username/URL to the Community Contributors list before I merge your PR?

It's like the public repo contributors list, but visible to readers of the website.

**Comment by tshepang** [comment]
i-done-it

**Comment by tnballo** [comment]
Sweet, thanks again - front page is the worst place for a typo :upside_down_face:

**Comment by tshepang** [comment]
you get such even in the very first line of important blog posts

**Pull request merged**
